# Generated by Django 4.2.5 on 2023-09-14 05:45

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('starts', '0001_initial'),
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='release_date')),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('release_year', models.PositiveIntegerField()),
                ('release_date', models.DateField(auto_now=True)),
                ('actors', models.ManyToManyField(related_name='movies', to='starts.actor')),
                ('director', models.ManyToManyField(related_name='movies', to='directors.director')),
                ('genres', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-release_year'],
                'indexes': [models.Index(fields=['-release_year'], name='movies_movi_release_10e022_idx')],
            },
        ),
    ]
