# Generated by Django 4.2.5 on 2023-09-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
